# Example config for upower-notify
# Copy this to ~/.config/upower-notify/config.toml and edit it to your likings

### The UPower device path.
device = "/org/freedesktop/UPower/devices/battery_BAT0"

### Action on events
#
# warning_level.low, warning_level.critical, and warning_level.action are pre-configured
#
# Possible entries:
# - warning_level.unknown
# - warning_level.none
# - warning_level.discharging
# - warning_level.low
# - warning_level.critical
# - warning_level.action
#
# - state.unknown
# - state.charging
# - state.discharging
# - state.empty
# - state.fully_charged
# - state.pending_charge
# - state.pending_discharge

[warning_level.none.exec]
commands = [] # A list of commands passed to `sh -c`

[warning_level.none.notification]
enable = false
summary = "Battery Discharging"
body = "Power levels normal."   # {time} and {percentage} are optional placeholders that will be substituted.
icon = "battery-good-symbolic"
timeout = 5000                  # in milliseconds
urgency = "low"                 # "low" | "normal" | "critical"
